import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_mail(email, feedback):
    login = "2ae67d66d3415d" # paste your login generated by Mailtrap
    password = "9f39fe71c5aa46" # paste your password generated by Mailtrap
    sender_email = "InJapanFeedback@blog.com"
    receiver_email = "InJapan@blog.com"
    message = MIMEMultipart("alternative")
    message["Subject"] = "Feedback Submission"
    message["From"] = sender_email
    message["To"] = receiver_email
    # write the plain text part
    text = f"""\
    New FeedBack Submission!
        Email: {email}
        Message: {feedback}"""
    # write the HTML part
    html = f"""\
    <html>
    <body>
        <h4>New Feedback Submission</h4>
        <ul><li>Email: {email}</li><li> Message: {feedback}</li></ul>
    </body>
    </html>
    """
    # convert both parts to MIMEText objects and add them to the MIMEMultipart message
    part1 = MIMEText(text, "plain")
    part2 = MIMEText(html, "html")
    message.attach(part1)
    message.attach(part2)
    # send your email
    with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
        server.login(login, password)
        server.sendmail(sender_email, receiver_email, message.as_string())
